env:
  browser: true
  es2021: true
extends:
  - google
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - simple-import-sort
rules: {
  "simple-import-sort/imports": "error",
  "simple-import-sort/exports": "error",
  "react/jsx-uses-react": "error",
  "react/jsx-uses-vars": "error",
}
settings:
  react: 
    version: detect